apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: springboot
  labels:
    app: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: springboot
          image: 192.168.157.136:80/repo/springboot:v6.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: springboot
  labels:
    app: springboot
spec:
  selector:
    app: springboot
  ports:
    - port: 8081
      targetPort: 8080
  type: ClusterIP
  clusterIP: 10.1.90.244
