spring:
  datasource:
    url: jdbc:mysql://192.168.157.131:3306/studentManager?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: z.336612
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info
